OPENAI_API_KEY=sk-AG0I2fc9rjAJyBUeoEVYaYnfkmteSipC
CODEX_API_KEY=sk-AG0I2fc9rjAJyBUeoEVYaYnfkmteSipC

ANTHROPIC_BASE_URL=https://api.deepseek.com/anthropic
ANTHROPIC_API_KEY=sk-1adbc5ffb65b4c0a88b9fc6ca34d6592

ANTHROPIC_MODEL=deepseek-v4-pro
ANTHROPIC_DEFAULT_OPUS_MODEL=deepseek-v4-pro
ANTHROPIC_DEFAULT_SONNET_MODEL=deepseek-v4-pro
ANTHROPIC_DEFAULT_HAIKU_MODEL=deepseek-v4-flash

CLAUDE_CODE_SUBAGENT_MODEL=deepseek-v4-flash
CLAUDE_CODE_EFFORT_LEVEL=max

NVM_DIR=/home/jiao/.nvm

JAVA_HOME=/usr/lib/jvm/java-11-openjdk

PATH=/home/jiao/.cargo/bin:/home/jiao/.local/share/coursier/bin:/home/jiao/xilinx/Vivado/2024.2/bin:/home/jiao/xilinx/Vitis/2024.2/bin:/home/jiao/xilinx/Vitis_HLS/2024.2/bin:/home/jiao/xilinx/.xinstall/Vivado_2024.2:/opt/cuda/bin:/opt/synopsys/vcs/W-2024.09-SP1/bin:/opt/synopsys/verdi/W-2024.09-SP1/bin:/opt/synopsys/scl/2024.06/linux64/bin:/usr/lib/jvm/java-11-openjdk/bin:/home/jiao/.nvm/versions/node/v22.16.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin

SYNOP_HOME=/opt/synopsys
VCS_HOME=/opt/synopsys/vcs/W-2024.09-SP1
VERDI_HOME=/opt/synopsys/verdi/W-2024.09-SP1
SCL_HOME=/opt/synopsys/scl/2024.06
LM_LICENSE_FILE=/opt/synopsys/scl/2024.06/admin/license/Synopsys.dat
SNPSLMD_LICENSE_FILE=27000@archlinux
VCS_ARCH_OVERRIDE=linux
VCS_NO_LINUX_CHECK=1
