[FileDialog]
history=file:///home/jiao/git/INT8-CIM-of-jiao/Thesis/start, file:///home/jiao/git/INT8-CIM-of-jiao/Thesis/middle/ppt, file:///home/jiao/Documents/xwechat_files/wxid_q0dg1boxp8sy22_18bc/msg/file/2026-05, file:///home/jiao/Downloads, file:///home/jiao/git
lastVisited=file:///home/jiao/Downloads
qtVersion=5.15.14
shortcuts=file:///, file:///home/jiao, file:///home/jiao/Documents, file:///home/jiao/Downloads, file:///home/jiao/Pictures, file:///home/jiao/Desktop
sidebarWidth=87
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)"
viewMode=Detail
